In [1]:
# Imported Library & Load the Processed Dataset

import pandas as pd

processed_df = pd.read_csv("../dataset/processed/train_processed.csv")

processed_df.head()

                                          final_text     label
0  yeah ‍️the guy wants to trend dat was why e jo...  negative
1  this life is so funny sef you will work hard a...  negative
2  dis is unfair of urcompany goingtowks nw ive b...  negative
3  lil wayne don vex me im actually not excited a...  negative
4  dis is unfair of ur company going to wks nw iv...  negative

In [2]:
# Check Dataset Information

processed_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4641 entries, 0 to 4640
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   final_text  4641 non-null   str
 1   label       4641 non-null   str
dtypes: str(2)
memory usage: 72.6 KB

In [3]:
processed_df.sample(5)

                                             final_text     label
3331  so at this sweet juncture its time to attack t...  positive
305   lol really though why una always dey give us m...  negative
2492  the kind sweat wey i don sweat today ehnnn eve...  negative
756   baba god you sabi as e be for my heart oo abeg...  negative
1344  awon china ti je eso ajara na china chop meet ...  negative

In [4]:
# Check Label Distribution Again

processed_df["label"].value_counts()

label
negative    3003
positive    1568
neutral       70
Name: count, dtype: int64

In [26]:
# Encode the Labels

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

processed_df["label_encoded"] = label_encoder.fit_transform(
    processed_df["label"]
)

In [27]:
processed_df.head()

                                          final_text     label  label_encoded
0  yeah ‍️the guy wants to trend dat was why e jo...  negative              0
1  this life is so funny sef you will work hard a...  negative              0
2  dis is unfair of urcompany goingtowks nw ive b...  negative              0
3  lil wayne don vex me im actually not excited a...  negative              0
4  dis is unfair of ur company going to wks nw iv...  negative              0

In [28]:
# Verify Encoding

label_encoder.classes_

array(['negative', 'neutral', 'positive'], dtype=object)

In [8]:
for index, label in enumerate(label_encoder.classes_):
    print(f"{label} --> {index}")

negative --> 0
neutral --> 1
positive --> 2

In [9]:
# Features 

X = processed_df["final_text"]

# Target

y = processed_df["label_encoded"]

In [10]:
print("Feature Shape:", X.shape)
print("Target Shape:", y.shape)

Feature Shape: (4641,)
Target Shape: (4641,)

In [11]:
X.head()

0    yeah ‍️the guy wants to trend dat was why e jo...
1    this life is so funny sef you will work hard a...
2    dis is unfair of urcompany goingtowks nw ive b...
3    lil wayne don vex me im actually not excited a...
4    dis is unfair of ur company going to wks nw iv...
Name: final_text, dtype: str

In [12]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: label_encoded, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
# Split the Dataset

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [15]:
# Verify the Split

print("Training Features:", X_train.shape)
print("Testing Features:", X_test.shape)

print("Training Labels  :", y_train.shape)
print("Testing Labels   :", y_test.shape)

Training Features: (3712,)
Testing Features: (929,)
Training Labels  : (3712,)
Testing Labels   : (929,)

In [16]:
# Confirm Class Distribution

print("Training Set:", )
print(y_train.value_counts())

print("\nTesting Set:")
print(y_test.value_counts())

Training Set:
label_encoded
0    2402
2    1254
1      56
Name: count, dtype: int64

Testing Set:
label_encoded
0    601
2    314
1     14
Name: count, dtype: int64

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize the Vectorizer
tfidf_vectorizer = TfidfVectorizer(
    max_features=5000
)

In [18]:
# Fit Only on Training Data

X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)

In [19]:
# Transform Test Data

X_test_tfidf = tfidf_vectorizer.transform(X_test)

In [20]:
# Check Matrix Shape

print("Training TF-IDF Shape:", X_train_tfidf.shape)
print("Testing TF-IDF Shape:", X_test_tfidf.shape)

Training TF-IDF Shape: (3712, 5000)
Testing TF-IDF Shape: (929, 5000)

In [21]:
# Inspect Learned Features

feature_names = tfidf_vectorizer.get_feature_names_out()

feature_names[:50]

array(['aap', 'aargh', 'aaswe', 'aba', 'abalu', 'abandoned', 'abattoir',
       'abaya', 'abayo', 'abbatoir', 'abbi', 'abd', 'abdomen',
       'abdullahi', 'abdulrazaq', 'abeg', 'abegi', 'abegii', 'abi',
       'abii', 'abj', 'able', 'abortion', 'about', 'above', 'abroad',
       'absolutely', 'abt', 'abu', 'abuja', 'abuse', 'ac', 'accent',
       'accept', 'access', 'account', 'accountable', 'acct', 'achieve',
       'across', 'act', 'action', 'activate', 'actually', 'ada', 'add',
       'added', 'address', 'adesua', 'admire'], dtype=object)

In [22]:
# Check Total Vocabulary Size

print("Total Features:", len(feature_names))

Total Features: 5000

In [29]:
import joblib

In [30]:
joblib.dump(
    tfidf_vectorizer,
    "../models/tfidf_vectorizer.joblib"
)

['../models/tfidf_vectorizer.joblib']

In [32]:
import joblib

joblib.dump(
    label_encoder,
    "../models/label_encoder.joblib"
)

['../models/label_encoder.joblib']

In [33]:
import os

print(os.path.getsize("../models/label_encoder.joblib"))

505

In [31]:
import os

os.listdir("../models")

['tfidf_vectorizer.joblib']

# Conclusion

In this notebook, the cleaned Nigerian Pidgin sentiment dataset was transformed into machine-readable numerical features.

Completed tasks:

- Loaded processed dataset
- Encoded sentiment labels
- Split data into training and testing sets
- Applied TF-IDF vectorization
- Generated numerical text representations
- Saved TF-IDF vectorizer
- Saved label encoder

The dataset is now ready for machine learning model training.